### ISSUE TITLE
Prefect examples doesn't work in Windows

### ISSUE THREAD

**Issue by aregm** [PrefectHQ/prefect-intel#18]
Installation with pip install git+https://github.com/PrefectHQ/prefect@orion-release-2.0a11 is successful. However

when trying to do 
`from prefect import flow, task`

get error message 

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Apps\Miniconda3\lib\site-packages\prefect\__init__.py", line 19, in <module>
    from prefect.logging.configuration import setup_logging
  File "C:\Apps\Miniconda3\lib\site-packages\prefect\logging\__init__.py", line 1, in <module>
    import prefect.logging.configuration
  File "C:\Apps\Miniconda3\lib\site-packages\prefect\logging\configuration.py", line 12, in <module>
    from prefect.utilities.collections import dict_to_flatdict, flatdict_to_dict
  File "C:\Apps\Miniconda3\lib\site-packages\prefect\utilities\__init__.py", line 5, in <module>
    import prefect.utilities.compat
  File "C:\Apps\Miniconda3\lib\site-packages\prefect\utilities\compat.py", line 120, in <module>
    from asyncio import ThreadedChildWatcher
ImportError: cannot import name 'ThreadedChildWatcher' from 'asyncio' (C:\Apps\Miniconda3\lib\asyncio\__init__.py)
`

Environment:
Windows 10, build 19044.1645
conda version 4.12.0
git version 2.36.1.windows.1
Python 3.10

**Comment by aregm** [comment]
Works with the 'orion' branch.
